baseURL = 'https://blog.john-ensley.com/'
languageCode = 'en-us'
title = 'Blog'
theme = "ink"
copyright = "© John Ensley"


pygmentsstyle = "friendly"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true


[params]
mode = "auto"
subtitle = "John Ensley"

# Optional 64x64 avatar image.
# avatar = "https://image.freepik.com/free-vector/young-man-head-with-beard-avatar-character_24877-36786.jpg"

featherIconsCDN = true


[taxonomies]
    tag = "tags"


[[params.social]]
name = "My homepage"
icon = "home"
url = "https://john-ensley.com"


[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/ensley/"


[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/john__ensley"


[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"


# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3


[deployment]
order = [".jpg$", ".gif$"]


[[deployment.targets]]
name = "s3deploy"
URL = "s3://blog.john-ensley.com?region=us-west-2"


[[deployment.matchers]]
# Cache static assets for 1 year.
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true


[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false


[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true
